// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9N3Fam3FH7fkCrqrGiGcofAyMjrFajGQ',
    appId: '1:374437620526:web:31427b44b944c69ad068bf',
    messagingSenderId: '374437620526',
    projectId: 'movieapp-572c6',
    authDomain: 'movieapp-572c6.firebaseapp.com',
    storageBucket: 'movieapp-572c6.firebasestorage.app',
    measurementId: 'G-4D1V3N3DMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9KGCQLYuSi4C4GjOb9-lIg9ohN9zHFHY',
    appId: '1:374437620526:android:bc419ff5c3cafa44d068bf',
    messagingSenderId: '374437620526',
    projectId: 'movieapp-572c6',
    storageBucket: 'movieapp-572c6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9N3Fam3FH7fkCrqrGiGcofAyMjrFajGQ',
    appId: '1:374437620526:web:899515ebf50333efd068bf',
    messagingSenderId: '374437620526',
    projectId: 'movieapp-572c6',
    authDomain: 'movieapp-572c6.firebaseapp.com',
    storageBucket: 'movieapp-572c6.firebasestorage.app',
    measurementId: 'G-TNTWYR3T13',
  );
}
